### ISSUE TITLE
It's having an issue. It gave me this error.

### ISSUE THREAD

**Issue by Bragsugar561930** [Cosmic-Infinity/WSA-Transfer#2]
C:\Users\User\Documents>echo
ECHO is on.

C:\Users\User\Documents>adb connect 127.0.0.1:58526
'adb' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User\Documents>adb -s 127.0.0.1:58526 push C:\Users\User\Pictures\no.png /sdcard/Download/
'adb' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\User\Documents>pause
Press any key to continue . . .

**Comment by Cosmic-Infinity** [comment]
Do you have adb installed on your system?

**Comment by Bragsugar561930** [comment]
> Do you have adb installed on your system?

Yes I do

**Comment by Cosmic-Infinity** [comment]
Then set environment variable to the location where you have kept the adb files.

Or you can follow along with [this tutorial](https://www.xda-developers.com/adb-fastboot-any-directory-windows-linux/) 

Once done, type 'adb' on the terminal and it should show something other than "not recognised". That should do it.

**Comment by Bragsugar561930** [comment]
> Then set environment variable to the location where you have kept the adb files.
> 
> Or you can follow along with [this tutorial](https://www.xda-developers.com/adb-fastboot-any-directory-windows-linux/)
> 
> Once done, type 'adb' on the terminal and it show show something other than "not recognised". That should do it.

Alright I’ll try this later. Thanks!

**Comment by Cosmic-Infinity** [comment]
I'm closing this issue for now. Though feel free to reopen if you need more help.

**Comment by Bragsugar561930** [comment]
> I'm closing this issue for now. Though feel free to reopen if you need more help.

Alright thanks that should help.
